import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function WhereWereYou() {
  return (
    <div>
      <Head>
        <title>NHL guess who</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>NHL games</h1>
      </section>

      <section className= {styles.container}>
        <table>
            <thead>
                <tr>
                <th>Company</th>
                <th>Contact</th>
                <th>Country</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
                <tr>
                <td>Centro comercial Moctezuma</td>
                <td>Francisco Chang</td>
                <td>Mexico</td>
                </tr>
            </tbody>
            </table>
      </section>
    </div>
  )
}